version: '3.8'

services:
  app:
    image: christracy/aprs-query
    restart: always
    environment:
      #SMTP Variables
      SMTP_USERNAME: <example@gmail.com>        # Email address used for processing
      SMTP_PASSWORD: <your secure password>             # Email password (app password)
      ALLOWED_DOMAINS: "winlink.org, example.com"  # Domains that are allowed to use the service. Use "*" to allow all domains
      
      #Open AI Variables
      OAI_API_KEY: <your open ai api key> #API key for Open AI

      #Open Weather Variables
      WEATHER_API_KEY: <your open weather map api key> # API key for Open Weather Map

      ### Optional parameters ###
      #IMAP_HOST: imap.gmail.com      # Change this to use something outside of gmail (not tested)
      #SMTP_HOST: smtp.gmail.com      # Change this to use something outside of gmail (not tested)
      #INTERVAL: 60                   # How often (seconds) to check the accounts inbox for new messages
      #RATE_LIMIT: 30                 # The number of seconds before a single account can email the service again. Violation = discard request without response
      #OAI_MODEL: gpt-3.5-turbo-0125  # GPT model to use for formating location to coordinates and units
      #OAI_MAX_TOKENS: 50             # Max tokens used to process the GPT request
      #LOG_LEVEL: INFO                # Log level for the server (INFO/DEBUG)